data <- read.csv(file.choose(), header = TRUE)
print(data)
kmeans.result<-kmeans(data,2)
plot(data[c("X1","X2")],col=kmeans.result$cluster)
points(kmeans.result$centers[,x("X1","X2")],col=1:3,pch=8,cex=2)
SimpleKMeans(data.control=NULL)